### PR TITLE
Overlay improvement

### PR DESCRIPTION
**Pull request by Shebuka**
Two simple changes that improve the overall look and feel:
- Additional shadow for `console-entry` so it is seen better over the game;
- Using a simple `grid` for `mission-heroes` that significantly improves visual layout.

### CODE REVIEW

**Comment by billw2012** [comment]
Please include screenshots/video/gif demonstrating the improvements. The shadows for the console entries have a trade off with performance, I did have more originally but removed them to improve perf when the heroes list is long also. 
Also I did of course try using grid, but twitch names are quite different lengths, and it also makes it more difficult for individuals to find themselves, as its harder to track changes when all the items are identical.

**Comment by Shebuka** [comment]
> The shadows for the console entries have a trade off with performance, I did have more originally but removed them to improve perf when the heroes list is long also.

This setting overrides the general one of bltconsole, so no new shadows, just a stronger one for the entries.



> Also I did of course try using grid, but twitch names are quite different lengths, and it also makes it more difficult for individuals to find themselves, as its harder to track changes when all the items are identical.

I found it way more difficult to track where my hero goes when there is a mayhem of constant change in position and all cells are of a different size. With a fixed grid position, it becomes way easier. In fact, I would love to have the option to disable sort per kill and just have the alphabet sort. Having a kill ranking has little use when viewers fatigue to track their heroes.

**Comment by billw2012** [comment]
On reflection I won't be accepting this unless the layout change is made as a configurable option, as inevitably with this kind of change some people like it how it was (including me, which is why I made it this way). 
Feel free to remake the PR if you make it optional. You can also split out the shadow change which I will accept IF you provide a comparative screenshot showing the improvement.

**Comment by Shebuka** [comment]
> the layout change is made as a configurable option, as inevitably with this kind of change some people like it how it was

How can I make an optional CSS change? Do you have a link or a guide on how to do it?

p.s. This is ok for 5-10 heroes playing with you. But did you seen the chaos of 50+ players in the list constantly jumping in sort order because their character or tenure made a kill? There is no way to track your hero health and power cooldown so this results in all 50+ players constantly spamming _use power_ and _heal_...

> IF you provide a comparative screenshot showing the improvement

I don't have the game installed right now... But it's a one-line change in the CSS, to speed things up, can you check out the branch and try it?

**Comment by billw2012** [comment]
So you could make it optional by just having it be a separate .css file, and anyone who wants it can just rename it (I will call it out in the change notes). This could be extended to allow selecting the "theme" in the BLTConfigure window, which would change which files get read in e.g. the `MissionInfo.Register` function.

**Comment by billw2012** [comment]
In fact, I quite like this idea of having themes. I could make it so that the UI files are all stored under a sub-directory with a theme name, then expose the list of available themes in the BLTConfigure window. That way people can create and share themes more easily, and there will be some more personalization in the overlay, anyone with the skills can make it fit in with their overall overlay theme.

**Comment by billw2012** [comment]
Yes. I will do this (or try) for the next release, and then you can release these changes as a theme. How does this sound?

**Pull request closed without merging**
